name: w2c-letsencrypt-esxi

# Make repo-wide default permissions explicit and minimal
permissions:
  contents: read

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Create VIB
        run: /bin/bash ./build/build.sh

      - name: Store VIB
        uses: actions/upload-artifact@v7.0.1
        with:
          name: w2c-letsencrypt-esxi
          path: |
            artifacts/w2c-letsencrypt-esxi-*-*.vib
            artifacts/w2c-letsencrypt-esxi-*-*-offline-bundle.zip
          if-no-files-found: error

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Retrieve build artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          name: w2c-letsencrypt-esxi
          path: artifacts

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: w2c-letsencrypt-esxi
          files: |
            artifacts/w2c-letsencrypt-esxi-*-*.vib
            artifacts/w2c-letsencrypt-esxi-*-*-offline-bundle.zip
